// Generated brand icon map (simple-icons). Monochrome paths rendered via BrandIcon.vue.
import {
  siVuedotjs,
  siLaravel,
  siPhp,
  siJavascript,
  siTypescript,
  siPython,
  siCplusplus,
  siC,
  siOpenjdk,
  siMysql,
  siPostgresql,
  siSqlite,
  siRedis,
  siElasticsearch,
  siDocker,
  siKubernetes,
  siNginx,
  siApache,
  siLinux,
  siUbuntu,
  siGit,
  siGithub,
  siGitlab,
  siTailwindcss,
  siVite,
  siReact,
  siBootstrap,
  siChartdotjs,
  siNodedotjs,
  siVercel,
  siCloudflare,
  siQuasar,
  siPinia,
  siFigma,
  siOpengl,
  siGrafana,
  siPrometheus,
  siRabbitmq,
  siApachekafka,
  siPytorch,
  siTensorflow,
  siHuggingface,
  siScikitlearn,
  siPandas,
  siNumpy,
  siLangchain,
  siGooglegemini,
  siOllama,
  siVitest,
  siEslint,
  siPrettier,
  siPostman,
  siNpm,
  siGnubash,
  siHtml5,
  siCss,
  siJira,
  siTrello,
  siAsana,
  siNotion,
  siWordpress,
  siShopify,
  siWix,
  siEbay,
  siPinterest,
  siInstagram,
  siFacebook,
  siTiktok,
  siX,
  siCodeforces,
  siHackerrank,
  siLeetcode,
  siUpwork,
  siGoogleanalytics,
  siSemrush,
  siMailchimp,
  siHootsuite,
  siBuffer,
  siMarkdown,
  siGraphql,
  siSwagger,
  siStripe,
  siFirebase,
  siSupabase,
} from 'simple-icons'

export type BrandIconData = {
  path: string
  hex: string
  title: string
}

export const BRAND_ICONS: Record<string, BrandIconData> = {
  vuedotjs: siVuedotjs,
  laravel: siLaravel,
  php: siPhp,
  javascript: siJavascript,
  typescript: siTypescript,
  python: siPython,
  cplusplus: siCplusplus,
  c: siC,
  openjdk: siOpenjdk,
  mysql: siMysql,
  postgresql: siPostgresql,
  sqlite: siSqlite,
  redis: siRedis,
  elasticsearch: siElasticsearch,
  docker: siDocker,
  kubernetes: siKubernetes,
  nginx: siNginx,
  apache: siApache,
  linux: siLinux,
  ubuntu: siUbuntu,
  git: siGit,
  github: siGithub,
  gitlab: siGitlab,
  tailwindcss: siTailwindcss,
  vite: siVite,
  react: siReact,
  bootstrap: siBootstrap,
  chartdotjs: siChartdotjs,
  nodedotjs: siNodedotjs,
  vercel: siVercel,
  cloudflare: siCloudflare,
  quasar: siQuasar,
  pinia: siPinia,
  figma: siFigma,
  opengl: siOpengl,
  grafana: siGrafana,
  prometheus: siPrometheus,
  rabbitmq: siRabbitmq,
  apachekafka: siApachekafka,
  pytorch: siPytorch,
  tensorflow: siTensorflow,
  huggingface: siHuggingface,
  scikitlearn: siScikitlearn,
  pandas: siPandas,
  numpy: siNumpy,
  langchain: siLangchain,
  googlegemini: siGooglegemini,
  ollama: siOllama,
  vitest: siVitest,
  eslint: siEslint,
  prettier: siPrettier,
  postman: siPostman,
  npm: siNpm,
  gnubash: siGnubash,
  html5: siHtml5,
  css: siCss,
  jira: siJira,
  trello: siTrello,
  asana: siAsana,
  notion: siNotion,
  wordpress: siWordpress,
  shopify: siShopify,
  wix: siWix,
  ebay: siEbay,
  pinterest: siPinterest,
  instagram: siInstagram,
  facebook: siFacebook,
  tiktok: siTiktok,
  x: siX,
  codeforces: siCodeforces,
  hackerrank: siHackerrank,
  leetcode: siLeetcode,
  upwork: siUpwork,
  googleanalytics: siGoogleanalytics,
  semrush: siSemrush,
  mailchimp: siMailchimp,
  hootsuite: siHootsuite,
  buffer: siBuffer,
  markdown: siMarkdown,
  graphql: siGraphql,
  swagger: siSwagger,
  stripe: siStripe,
  firebase: siFirebase,
  supabase: siSupabase,
}

export function getBrandIcon(slug?: string | null): BrandIconData | undefined {
  if (!slug) return undefined
  return BRAND_ICONS[slug]
}
