// Generated brand icon map (simple-icons subset). Monochrome paths rendered via BrandIcon.vue.
import { SIMPLE_ICON_SUBSET as icons } from './simpleIconSubset'

export type BrandIconData = {
  path: string
  hex: string
  title: string
}

export const BRAND_ICONS: Record<string, BrandIconData> = {
  vuedotjs: icons.siVuedotjs,
  laravel: icons.siLaravel,
  php: icons.siPhp,
  javascript: icons.siJavascript,
  typescript: icons.siTypescript,
  python: icons.siPython,
  cplusplus: icons.siCplusplus,
  c: icons.siC,
  openjdk: icons.siOpenjdk,
  mysql: icons.siMysql,
  postgresql: icons.siPostgresql,
  sqlite: icons.siSqlite,
  redis: icons.siRedis,
  elasticsearch: icons.siElasticsearch,
  docker: icons.siDocker,
  kubernetes: icons.siKubernetes,
  nginx: icons.siNginx,
  apache: icons.siApache,
  linux: icons.siLinux,
  ubuntu: icons.siUbuntu,
  git: icons.siGit,
  github: icons.siGithub,
  gitlab: icons.siGitlab,
  tailwindcss: icons.siTailwindcss,
  vite: icons.siVite,
  react: icons.siReact,
  nextdotjs: icons.siNextdotjs,
  nuxtdotjs: icons.siNuxt,
  nuxt: icons.siNuxt,
  nestjs: icons.siNestjs,
  express: icons.siExpress,
  axios: icons.siAxios,
  fastapi: icons.siFastapi,
  springboot: icons.siSpringboot,
  spring: icons.siSpringboot,
  dotnet: icons.siDotnet,
  anthropic: icons.siAnthropic,
  bootstrap: icons.siBootstrap,
  chartdotjs: icons.siChartdotjs,
  nodedotjs: icons.siNodedotjs,
  vercel: icons.siVercel,
  cloudflare: icons.siCloudflare,
  quasar: icons.siQuasar,
  pinia: icons.siPinia,
  figma: icons.siFigma,
  opengl: icons.siOpengl,
  grafana: icons.siGrafana,
  prometheus: icons.siPrometheus,
  opentelemetry: icons.siOpentelemetry,
  githubactions: icons.siGithubactions,
  rabbitmq: icons.siRabbitmq,
  apachekafka: icons.siApachekafka,
  pytorch: icons.siPytorch,
  tensorflow: icons.siTensorflow,
  huggingface: icons.siHuggingface,
  scikitlearn: icons.siScikitlearn,
  pandas: icons.siPandas,
  numpy: icons.siNumpy,
  langchain: icons.siLangchain,
  googlegemini: icons.siGooglegemini,
  ollama: icons.siOllama,
  vitest: icons.siVitest,
  eslint: icons.siEslint,
  prettier: icons.siPrettier,
  postman: icons.siPostman,
  npm: icons.siNpm,
  gnubash: icons.siGnubash,
  html5: icons.siHtml5,
  css: icons.siCss,
  jira: icons.siJira,
  trello: icons.siTrello,
  asana: icons.siAsana,
  notion: icons.siNotion,
  wordpress: icons.siWordpress,
  shopify: icons.siShopify,
  wix: icons.siWix,
  ebay: icons.siEbay,
  pinterest: icons.siPinterest,
  instagram: icons.siInstagram,
  facebook: icons.siFacebook,
  tiktok: icons.siTiktok,
  x: icons.siX,
  codeforces: icons.siCodeforces,
  hackerrank: icons.siHackerrank,
  leetcode: icons.siLeetcode,
  upwork: icons.siUpwork,
  googleanalytics: icons.siGoogleanalytics,
  semrush: icons.siSemrush,
  mailchimp: icons.siMailchimp,
  hootsuite: icons.siHootsuite,
  buffer: icons.siBuffer,
  markdown: icons.siMarkdown,
  graphql: icons.siGraphql,
  mqtt: icons.siMqtt,
  socketdotio: icons.siSocketdotio,
  swagger: icons.siSwagger,
  stripe: icons.siStripe,
  firebase: icons.siFirebase,
  supabase: icons.siSupabase,
}

export function getBrandIcon(slug?: string | null): BrandIconData | undefined {
  if (!slug) return undefined
  return BRAND_ICONS[slug]
}
