import type { IndustryTopic } from '../topic-types'

const topics: IndustryTopic[] = [
  {
    id: 'idempotency-keys-for-payments',
    slug: 'idempotency-keys-for-payments',
    domain: 'api-integration',
    titles: {
      en: 'Idempotency keys for payment APIs',
      bn: 'Payment API-তে idempotency key',
    },
    summary: {
      en: 'How a single retried POST becomes a double charge, and the key-scoped record that makes replay safe.',
      bn: 'একটি retried POST কীভাবে double charge হয়, আর key-scoped record কীভাবে replay নিরাপদ করে।',
    },
    tags: ['idempotency', 'payments', 'retries', 'http', 'concurrency'],
    difficulty: 'advanced',
    status: 'full',
    related: ['retry-with-jitter-strategy', 'bulk-endpoints-partial-failure'],
    systemsLinks: ['idempotency-keys'],
  },
  {
    id: 'timeout-budget-propagation',
    slug: 'timeout-budget-propagation',
    domain: 'api-integration',
    titles: {
      en: 'Timeout budget propagation across hops',
      bn: 'Hop জুড়ে timeout budget propagation',
    },
    summary: {
      en: 'Why every service having its own 30s timeout guarantees the client gives up before anyone answers.',
      bn: 'প্রতি service-এর নিজস্ব ৩০s timeout থাকলে উত্তর আসার আগেই client কেন হাল ছাড়ে।',
    },
    tags: ['timeouts', 'deadlines', 'latency', 'tracing'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['retry-with-jitter-strategy', 'third-party-outage-degradation'],
    systemsLinks: ['circuit-breaker', 'littles-law'],
  },
  {
    id: 'retry-with-jitter-strategy',
    slug: 'retry-with-jitter-strategy',
    domain: 'api-integration',
    titles: {
      en: 'Retry with jitter, budgets, and honest error classes',
      bn: 'Jitter, budget ও সৎ error class সহ retry',
    },
    summary: {
      en: 'Exponential backoff alone still synchronises clients - jitter, retry budgets, and which status codes are safe to repeat.',
      bn: 'শুধু exponential backoff client sync করেই ফেলে - jitter, retry budget, আর কোন status code repeat করা নিরাপদ।',
    },
    tags: ['retries', 'backoff', 'jitter', 'resilience'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['circuit-breaker-cascades', 'timeout-budget-propagation'],
    systemsLinks: ['thundering-herd', 'circuit-breaker'],
  },
  {
    id: 'rate-limiting-algorithms',
    slug: 'rate-limiting-algorithms',
    domain: 'api-integration',
    titles: {
      en: 'Rate limiting algorithms and fair quotas',
      bn: 'Rate limiting algorithm ও fair quota',
    },
    summary: {
      en: 'Fixed window, sliding log, token bucket, leaky bucket - and the headers clients need to behave.',
      bn: 'fixed window, sliding log, token bucket, leaky bucket - আর client-কে ভদ্র রাখার header।',
    },
    tags: ['rate-limiting', 'token-bucket', 'leaky-bucket', 'quotas', 'redis'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['retry-with-jitter-strategy', 'graphql-depth-and-n-plus-one'],
    systemsLinks: ['rate-limiting'],
  },
  {
    id: 'webhook-delivery-reliability',
    slug: 'webhook-delivery-reliability',
    domain: 'api-integration',
    titles: {
      en: 'Webhook delivery you can actually trust',
      bn: 'ভরসা করা যায় এমন webhook delivery',
    },
    summary: {
      en: 'Signed payloads, at-least-once redelivery, ordering claims you should not make, and the dead letter queue.',
      bn: 'signed payload, at-least-once redelivery, যে ordering claim করা উচিত নয়, আর dead letter queue।',
    },
    tags: ['webhooks', 'delivery', 'signing', 'dlq', 'outbox'],
    difficulty: 'advanced',
    status: 'full',
    related: ['idempotency-keys-for-payments', 'retry-with-jitter-strategy'],
    systemsLinks: ['outbox-pattern', 'poison-pills'],
  },
  {
    id: 'api-versioning-without-breakage',
    slug: 'api-versioning-without-breakage',
    domain: 'api-integration',
    titles: {
      en: 'API versioning without breaking callers',
      bn: 'Caller না ভেঙে API versioning',
    },
    summary: {
      en: 'Additive change rules, version pinning, deprecation windows, and the Sunset header nobody reads.',
      bn: 'additive change rule, version pinning, deprecation window, আর কেউ না পড়া Sunset header।',
    },
    tags: ['versioning', 'contracts', 'deprecation', 'http'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['contract-testing-across-teams', 'pagination-at-scale'],
    systemsLinks: ['feature-flags'],
  },
  {
    id: 'pagination-at-scale',
    slug: 'pagination-at-scale',
    domain: 'api-integration',
    titles: {
      en: 'Pagination at scale: offsets, cursors, and drift',
      bn: 'Scale-এ pagination: offset, cursor ও drift',
    },
    summary: {
      en: 'Why OFFSET 200000 melts the database and how keyset cursors keep page 4000 as cheap as page 1.',
      bn: 'OFFSET 200000 কেন database গলিয়ে দেয় আর keyset cursor কীভাবে page 4000-কে page 1-এর মতো সস্তা রাখে।',
    },
    tags: ['pagination', 'cursors', 'sql', 'indexes'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['bulk-endpoints-partial-failure', 'rate-limiting-algorithms'],
    systemsLinks: ['hotspot-keys'],
  },
  {
    id: 'bulk-endpoints-partial-failure',
    slug: 'bulk-endpoints-partial-failure',
    domain: 'api-integration',
    titles: {
      en: 'Bulk endpoints and partial failure semantics',
      bn: 'Bulk endpoint ও partial failure semantics',
    },
    summary: {
      en: 'One request, 500 items, 7 failures - what status code do you return and what does the client retry?',
      bn: 'এক request, ৫০০ item, ৭টি failure - কোন status code ফেরাবেন আর client কী retry করবে?',
    },
    tags: ['bulk-api', 'partial-failure', 'idempotency', 'http', 'batching'],
    difficulty: 'advanced',
    status: 'full',
    related: ['idempotency-keys-for-payments', 'pagination-at-scale'],
    systemsLinks: ['idempotency-keys', 'saga-pattern'],
  },
  {
    id: 'third-party-outage-degradation',
    slug: 'third-party-outage-degradation',
    domain: 'api-integration',
    titles: {
      en: 'Graceful degradation when a vendor goes down',
      bn: 'Vendor down হলে graceful degradation',
    },
    summary: {
      en: 'Classifying dependencies as critical or optional, and shipping the fallback path before the vendor status page turns orange.',
      bn: 'dependency-কে critical/optional ভাগ করা, আর vendor status page কমলা হওয়ার আগেই fallback path ship করা।',
    },
    tags: ['degradation', 'vendors', 'fallbacks', 'circuit-breaker', 'slo'],
    difficulty: 'advanced',
    status: 'full',
    related: ['circuit-breaker-cascades', 'timeout-budget-propagation'],
    systemsLinks: ['circuit-breaker', 'feature-flags'],
  },
  {
    id: 'graphql-depth-and-n-plus-one',
    slug: 'graphql-depth-and-n-plus-one',
    domain: 'api-integration',
    titles: {
      en: 'GraphQL query depth and the N+1 tax',
      bn: 'GraphQL query depth ও N+1 tax',
    },
    summary: {
      en: 'A 12-line query can issue 4,000 SQL statements - depth limits, cost analysis, and batched loaders.',
      bn: '১২ লাইনের query ৪,০০০ SQL চালাতে পারে - depth limit, cost analysis ও batched loader।',
    },
    tags: ['graphql', 'n-plus-one', 'dataloader', 'query-cost'],
    difficulty: 'advanced',
    status: 'full',
    related: ['pagination-at-scale', 'rate-limiting-algorithms'],
    systemsLinks: ['rate-limiting'],
  },
  {
    id: 'contract-testing-across-teams',
    slug: 'contract-testing-across-teams',
    domain: 'api-integration',
    titles: {
      en: 'Contract testing across team boundaries',
      bn: 'Team boundary জুড়ে contract testing',
    },
    summary: {
      en: 'Consumer-driven contracts, provider verification in CI, and stopping the integration-environment guessing game.',
      bn: 'consumer-driven contract, CI-তে provider verification, আর integration environment-এর আন্দাজ খেলা বন্ধ করা।',
    },
    tags: ['contract-testing', 'openapi', 'ci', 'pact'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['api-versioning-without-breakage', 'webhook-delivery-reliability'],
    systemsLinks: ['blue-green-canary'],
  },
]

export default topics
