import type { IndustryTopic } from '../topic-types'

/** Caching & CDN wave — cache layer failure modes from origin to edge. */
const topics: IndustryTopic[] = [
  {
    id: 'cache-stampede-prevention',
    slug: 'cache-stampede-prevention',
    domain: 'caching-cdn',
    titles: {
      en: 'Cache stampede prevention with locks and early refresh',
      bn: 'lock ও early refresh দিয়ে cache stampede প্রতিরোধ',
    },
    summary: {
      en: 'One hot key expires and every request hits the origin at once — single-flight locks, probabilistic early expiry, and stale serving keep the database alive.',
      bn: 'একটি hot key expire হলেই সব request একসাথে origin-এ যায় — single-flight lock, probabilistic early expiry ও stale serving database বাঁচায়।',
    },
    tags: ['cache', 'stampede', 'redis', 'locking', 'thundering-herd'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['ttl-and-jitter-design', 'stale-while-revalidate-patterns', 'cache-invalidation-strategies'],
    systemsLinks: ['cache-stampede', 'thundering-herd'],
  },
  {
    id: 'cache-aside-vs-write-through',
    slug: 'cache-aside-vs-write-through',
    domain: 'caching-cdn',
    titles: {
      en: 'Cache-aside vs write-through vs write-behind',
      bn: 'Cache-aside vs write-through vs write-behind',
    },
    summary: {
      en: 'Three write paths with three different staleness and data-loss profiles — and the race that makes cache-aside serve a value the database never had.',
      bn: 'তিনটি write path, তিন রকম staleness ও data-loss profile — এবং যে race cache-aside-কে database-এ কখনো না থাকা value serve করায়।',
    },
    tags: ['cache-aside', 'write-through', 'write-behind', 'consistency'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['distributed-cache-consistency', 'cache-invalidation-strategies', 'negative-caching-null-results'],
    systemsLinks: ['outbox-pattern'],
  },
  {
    id: 'ttl-and-jitter-design',
    slug: 'ttl-and-jitter-design',
    domain: 'caching-cdn',
    titles: {
      en: 'TTL and jitter design for cache fleets',
      bn: 'cache fleet-এর জন্য TTL ও jitter design',
    },
    summary: {
      en: 'Round-number TTLs set during a deploy expire together forever — how to pick a TTL from your tolerance for staleness and spread expiry across the window.',
      bn: 'deploy-এ সেট করা round-number TTL চিরকাল একসাথে expire হয় — staleness tolerance থেকে TTL বাছাই ও expiry ছড়িয়ে দেওয়ার উপায়।',
    },
    tags: ['ttl', 'jitter', 'expiry', 'redis'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['cache-stampede-prevention', 'stale-while-revalidate-patterns', 'cache-eviction-policy-choice'],
    systemsLinks: ['thundering-herd', 'cache-stampede'],
  },
  {
    id: 'negative-caching-null-results',
    slug: 'negative-caching-null-results',
    domain: 'caching-cdn',
    titles: {
      en: 'Negative caching for null and 404 results',
      bn: 'null ও 404 result-এর negative caching',
    },
    summary: {
      en: 'Misses that are never cached become an unbounded origin load channel — and a scanning attack surface. Cache the absence, but with a shorter TTL.',
      bn: 'যে miss কখনো cache হয় না তা unbounded origin load channel ও scanning attack surface — absence cache করুন, তবে ছোট TTL দিয়ে।',
    },
    tags: ['negative-caching', 'null-cache', 'bloom-filter', 'penetration'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['cache-aside-vs-write-through', 'ttl-and-jitter-design', 'cache-stampede-prevention'],
    systemsLinks: ['thundering-herd'],
  },
  {
    id: 'cdn-cache-key-normalization',
    slug: 'cdn-cache-key-normalization',
    domain: 'caching-cdn',
    titles: {
      en: 'CDN cache key normalization and hit ratio',
      bn: 'CDN cache key normalization ও hit ratio',
    },
    summary: {
      en: 'Tracking query strings, sloppy Vary headers, and cookies fragment one object into thousands of variants — hit ratio collapses and the origin pays.',
      bn: 'tracking query string, ঢিলেঢালা Vary header ও cookie একটি object-কে হাজারো variant-এ ভাঙে — hit ratio পড়ে যায়, origin দাম দেয়।',
    },
    tags: ['cdn', 'cache-key', 'vary', 'hit-ratio', 'nginx'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['edge-caching-personalized-content', 'stale-while-revalidate-patterns', 'cache-invalidation-strategies'],
    systemsLinks: [],
  },
  {
    id: 'stale-while-revalidate-patterns',
    slug: 'stale-while-revalidate-patterns',
    domain: 'caching-cdn',
    titles: {
      en: 'stale-while-revalidate and stale-if-error patterns',
      bn: 'stale-while-revalidate ও stale-if-error pattern',
    },
    summary: {
      en: 'Serving slightly old bytes instantly beats serving fresh bytes in 900 ms — and stale-if-error turns an origin outage into a cosmetic problem.',
      bn: '900 ms-এ fresh bytes দেওয়ার চেয়ে সামান্য পুরনো bytes তৎক্ষণাৎ দেওয়া ভালো — stale-if-error origin outage-কে cosmetic সমস্যায় নামায়।',
    },
    tags: ['swr', 'cache-control', 'cdn', 'availability'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['ttl-and-jitter-design', 'cdn-cache-key-normalization', 'cache-stampede-prevention'],
    systemsLinks: ['cache-stampede'],
  },
  {
    id: 'distributed-cache-consistency',
    slug: 'distributed-cache-consistency',
    domain: 'caching-cdn',
    titles: {
      en: 'Distributed cache consistency across regions',
      bn: 'region জুড়ে distributed cache consistency',
    },
    summary: {
      en: 'Local in-process caches, a regional Redis, and a CDN each hold a different version of the truth — invalidation ordering decides who sees ghosts.',
      bn: 'local in-process cache, regional Redis ও CDN — প্রত্যেকে ভিন্ন version ধরে রাখে; invalidation ordering ঠিক করে কে ghost দেখবে।',
    },
    tags: ['consistency', 'invalidation', 'multi-region', 'redis', 'pubsub'],
    difficulty: 'advanced',
    status: 'full',
    related: ['cache-aside-vs-write-through', 'cache-invalidation-strategies', 'redis-hot-key-sharding'],
    systemsLinks: ['cap-theorem', 'multi-region'],
  },
  {
    id: 'redis-hot-key-sharding',
    slug: 'redis-hot-key-sharding',
    domain: 'caching-cdn',
    titles: {
      en: 'Redis hot key sharding and client-side caching',
      bn: 'Redis hot key sharding ও client-side caching',
    },
    summary: {
      en: 'A single viral key pins one shard to 100% CPU while the rest of the cluster idles — key splitting, replica fanout, and a small local L1.',
      bn: 'একটি viral key এক shard-কে 100% CPU-তে আটকায়, বাকি cluster বসে থাকে — key splitting, replica fanout ও ছোট local L1।',
    },
    tags: ['redis', 'hot-key', 'sharding', 'cluster', 'hotspot'],
    difficulty: 'advanced',
    status: 'full',
    related: ['cache-eviction-policy-choice', 'distributed-cache-consistency', 'cache-stampede-prevention'],
    systemsLinks: ['hotspot-keys'],
  },
  {
    id: 'cache-eviction-policy-choice',
    slug: 'cache-eviction-policy-choice',
    domain: 'caching-cdn',
    titles: {
      en: 'Choosing a cache eviction policy that matches your workload',
      bn: 'workload অনুযায়ী cache eviction policy বাছাই',
    },
    summary: {
      en: 'noeviction turns a full Redis into a write outage; allkeys-lru throws away the session you needed. Pick per keyspace, not per cluster.',
      bn: 'noeviction ভরা Redis-কে write outage বানায়; allkeys-lru দরকারি session ফেলে দেয়। cluster নয়, keyspace ধরে বাছুন।',
    },
    tags: ['eviction', 'lru', 'lfu', 'redis', 'memory'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['redis-hot-key-sharding', 'ttl-and-jitter-design', 'cache-warming-after-deploy'],
    systemsLinks: ['hotspot-keys'],
  },
  {
    id: 'edge-caching-personalized-content',
    slug: 'edge-caching-personalized-content',
    domain: 'caching-cdn',
    titles: {
      en: 'Edge caching personalized content without leaking it',
      bn: 'leak ছাড়াই personalized content edge-এ cache করা',
    },
    summary: {
      en: 'One missing Cache-Control: private and user A gets user B’s dashboard from the shared edge — segment keys, ESI holes, and client-side hydration instead.',
      bn: 'একটি Cache-Control: private বাদ পড়লেই shared edge থেকে user A পায় user B-র dashboard — বদলে segment key, ESI hole ও client-side hydration।',
    },
    tags: ['cdn', 'personalization', 'privacy', 'vary', 'esi'],
    difficulty: 'advanced',
    status: 'full',
    related: ['cdn-cache-key-normalization', 'stale-while-revalidate-patterns', 'distributed-cache-consistency'],
    systemsLinks: ['feature-flags'],
  },
  {
    id: 'cache-warming-after-deploy',
    slug: 'cache-warming-after-deploy',
    domain: 'caching-cdn',
    titles: {
      en: 'Cache warming after deploy and cold-start collapse',
      bn: 'deploy-পরবর্তী cache warming ও cold-start collapse',
    },
    summary: {
      en: 'A key-prefix version bump empties the cache at peak traffic and the database falls over 40 seconds later — warm before you shift traffic.',
      bn: 'peak traffic-এ key-prefix version bump cache খালি করে, 40 সেকেন্ড পর database পড়ে যায় — traffic shift-এর আগে warm করুন।',
    },
    tags: ['cache-warming', 'deploy', 'cold-start', 'canary'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['cache-stampede-prevention', 'cache-eviction-policy-choice', 'cache-invalidation-strategies'],
    systemsLinks: ['thundering-herd', 'blue-green-canary'],
  },
]

export default topics
