import type { IndustryTopic } from '../topic-types'

const topics: IndustryTopic[] = [
  {
    id: 'etl-vs-elt-decisions',
    slug: 'etl-vs-elt-decisions',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'ETL vs ELT: choosing where transformation lives',
      bn: 'ETL vs ELT: transformation কোথায় থাকবে',
    },
    summary: {
      en: 'Transforming before load hides raw evidence; transforming after load buys warehouse compute - the tradeoff decides how fast you can fix a bad column.',
      bn: 'load-এর আগে transform করলে raw evidence হারায়; পরে করলে warehouse compute কেনা লাগে - এই tradeoff-ই ঠিক করে bad column কত দ্রুত ঠিক হবে।',
    },
    tags: ['etl', 'elt', 'warehouse', 'dbt', 'modeling'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['data-quality-contracts', 'batch-vs-streaming-pipelines', 'idempotent-backfills'],
    systemsLinks: [],
  },
  {
    id: 'idempotent-backfills',
    slug: 'idempotent-backfills',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Idempotent backfills that can be re-run safely',
      bn: 'নিরাপদে re-run করা যায় এমন idempotent backfill',
    },
    summary: {
      en: 'A backfill that appends instead of replacing turns one bug into double-counted revenue across 90 partitions.',
      bn: 'replace-এর বদলে append করা backfill একটি bug-কে ৯০টি partition জুড়ে double-counted revenue বানায়।',
    },
    tags: ['backfill', 'idempotency', 'partitions', 'airflow', 'sql'],
    difficulty: 'advanced',
    status: 'full',
    related: ['pipeline-orchestration-retries', 'late-arriving-out-of-order-data'],
    systemsLinks: ['idempotency-keys'],
  },
  {
    id: 'feature-store-consistency',
    slug: 'feature-store-consistency',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Feature store consistency: offline vs online',
      bn: 'Feature store consistency: offline vs online',
    },
    summary: {
      en: 'Point-in-time correctness, one transform definition, and why a 30-minute-stale online feature quietly halves precision.',
      bn: 'point-in-time correctness, একটাই transform definition, আর ৩০ মিনিট stale online feature কেন নীরবে precision অর্ধেক করে।',
    },
    tags: ['feature-store', 'mlops', 'point-in-time', 'serving'],
    difficulty: 'advanced',
    status: 'full',
    related: ['training-serving-skew', 'data-quality-contracts', 'model-versioning-and-rollback'],
    systemsLinks: ['outbox-pattern'],
  },
  {
    id: 'data-quality-contracts',
    slug: 'data-quality-contracts',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Data quality contracts between producers and consumers',
      bn: 'Producer ও consumer-এর মধ্যে data quality contract',
    },
    summary: {
      en: 'Expectations as code, blocking vs warning severities, and who gets paged when a nullable column starts being null.',
      bn: 'expectation as code, blocking vs warning severity, আর nullable column সত্যিই null হলে কাকে page করা হবে।',
    },
    tags: ['data-quality', 'contracts', 'great-expectations', 'testing', 'sla'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['schema-drift-detection', 'etl-vs-elt-decisions', 'feature-store-consistency'],
    systemsLinks: ['golden-signals'],
  },
  {
    id: 'schema-drift-detection',
    slug: 'schema-drift-detection',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Schema drift detection before it reaches the model',
      bn: 'Model-এ পৌঁছার আগে schema drift শনাক্ত',
    },
    summary: {
      en: 'An upstream rename ships on Tuesday, your dashboard is empty on Friday - registries, compatibility modes, and quarantine paths.',
      bn: 'মঙ্গলবারে upstream rename, শুক্রবারে dashboard খালি - registry, compatibility mode, quarantine path।',
    },
    tags: ['schema', 'drift', 'avro', 'registry', 'validation'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['data-quality-contracts', 'pipeline-orchestration-retries'],
    systemsLinks: ['poison-pills'],
  },
  {
    id: 'late-arriving-out-of-order-data',
    slug: 'late-arriving-out-of-order-data',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Late-arriving and out-of-order data',
      bn: 'দেরিতে আসা ও out-of-order data',
    },
    summary: {
      en: 'Event time vs processing time, watermarks, allowed lateness, and why a mobile client offline for six hours breaks yesterday’s totals.',
      bn: 'event time vs processing time, watermark, allowed lateness, আর ছয় ঘণ্টা offline mobile client কেন গতকালের total ভাঙে।',
    },
    tags: ['event-time', 'watermarks', 'streaming', 'windowing'],
    difficulty: 'advanced',
    status: 'full',
    related: ['batch-vs-streaming-pipelines', 'idempotent-backfills'],
    systemsLinks: ['clock-skew'],
  },
  {
    id: 'batch-vs-streaming-pipelines',
    slug: 'batch-vs-streaming-pipelines',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Batch vs streaming: picking the cheaper correctness',
      bn: 'Batch vs streaming: সস্তা correctness বেছে নেওয়া',
    },
    summary: {
      en: 'Freshness requirements, not fashion, decide the engine - and most teams need one streaming path plus a batch reconciler.',
      bn: 'fashion নয়, freshness requirement engine ঠিক করে - বেশিরভাগ team-এর একটি streaming path ও একটি batch reconciler লাগে।',
    },
    tags: ['batch', 'streaming', 'kafka', 'freshness', 'architecture'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['late-arriving-out-of-order-data', 'etl-vs-elt-decisions', 'pipeline-orchestration-retries'],
    systemsLinks: ['backpressure', 'message-queues'],
  },
  {
    id: 'model-versioning-and-rollback',
    slug: 'model-versioning-and-rollback',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Model versioning and rollback under fire',
      bn: 'চাপের মধ্যে model versioning ও rollback',
    },
    summary: {
      en: 'A checkpoint file is not a version - you need the code, the feature spec, the label snapshot, and a one-command way back.',
      bn: 'checkpoint file মানেই version নয় - code, feature spec, label snapshot, আর এক command-এ ফেরার পথ লাগে।',
    },
    tags: ['mlops', 'versioning', 'rollback', 'registry', 'shadow-deploy'],
    difficulty: 'advanced',
    status: 'full',
    related: ['training-serving-skew', 'feature-store-consistency', 'imbalanced-classification-strategies'],
    systemsLinks: ['blue-green-canary', 'feature-flags'],
  },
  {
    id: 'imbalanced-classification-strategies',
    slug: 'imbalanced-classification-strategies',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Imbalanced classification: 12 classes, one loud majority',
      bn: 'Imbalanced classification: ১২ class, একটাই সরব majority',
    },
    summary: {
      en: 'Class weights, focal loss, resampling, and threshold tuning on a 27k-sample multi-class text set where accuracy lies by 30 points.',
      bn: '২৭k sample-এর multi-class text set-এ class weight, focal loss, resampling ও threshold tuning - যেখানে accuracy ৩০ point মিথ্যা বলে।',
    },
    tags: ['classification', 'imbalance', 'focal-loss', 'f1', 'pytorch'],
    difficulty: 'advanced',
    status: 'full',
    related: ['model-versioning-and-rollback', 'data-quality-contracts', 'training-serving-skew'],
    systemsLinks: [],
  },
  {
    id: 'pipeline-orchestration-retries',
    slug: 'pipeline-orchestration-retries',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'Pipeline orchestration retries that do not amplify',
      bn: 'Amplify না করা pipeline orchestration retry',
    },
    summary: {
      en: 'Task-level retries, sensor storms, and the difference between retrying a step and re-running a DAG run.',
      bn: 'task-level retry, sensor storm, আর একটি step retry বনাম পুরো DAG run re-run-এর পার্থক্য।',
    },
    tags: ['airflow', 'orchestration', 'retries', 'sla', 'dag'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['idempotent-backfills', 'schema-drift-detection', 'batch-vs-streaming-pipelines'],
    systemsLinks: ['circuit-breaker', 'thundering-herd'],
  },
  {
    id: 'pii-handling-in-pipelines',
    slug: 'pii-handling-in-pipelines',
    domain: 'data-pipelines-ml',
    titles: {
      en: 'PII handling in analytics and training pipelines',
      bn: 'Analytics ও training pipeline-এ PII handling',
    },
    summary: {
      en: 'Tagging at ingestion, tokenising instead of hashing, and why deletion requests are a pipeline design constraint.',
      bn: 'ingestion-এ tagging, hash নয় tokenise, আর deletion request কেন pipeline design constraint।',
    },
    tags: ['pii', 'privacy', 'gdpr', 'tokenisation', 'governance'],
    difficulty: 'intermediate',
    status: 'full',
    related: ['data-quality-contracts', 'etl-vs-elt-decisions', 'feature-store-consistency'],
    systemsLinks: [],
  },
]

export default topics
